os: linux
dist: ubuntu
language:
  python
python:
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - sudo apt-get install sqlite3
install:
  - sudo pip3 install django
before_script:
  - python3 manage.py makemigrations LegacySite
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - sh import_dbs.sh
script:
  - python3 manage.py test
